// Generated by CoffeeScript 1.10.0
(function() {
  var fs;

  fs = require('fs');

  module.exports = {
    name: 'package.json',
    read_type: 'file',
    filters: function(app) {
      return [
        {
          name: 'JSON',
          extensions: ['json']
        }, {
          name: 'All files',
          extensions: ['*']
        }
      ];
    },
    load: function(app) {
      return app.editor().setValue(JSON.parse(fs.readFileSync(app.target(), {
        encoding: 'utf8'
      })));
    },
    save: function(app) {
      return fs.writeFileSync(app.target(), JSON.stringify(app.editor().getValue(), null, '  '));
    },
    schema: function(app) {
      return require('./package.json.schema.json');
    }
  };

}).call(this);
